---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart ambari-server
  service:
    name: ambari-server
    state: restarted
    enabled: yes

- name: Restart ambari-agent
  service:
    name: ambari-agent
    state: restarted
    enabled: yes