---
- name: Install packages
  include_tasks: install-packages-redhat.yml

- name: Create temp directory
  file:
    path: '{{ guacamole_temp_path }}'
    state: directory
  changed_when: False

- name: Install guacamole server
  include_tasks: install-guacamole-server.yml

- name: Install guacamole client
  include_tasks: install-guacamole-client.yml

- name: Start and enable guacd on startup
  systemd: 
    name: guacd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Clean up temporary files
  file:
    path: '{{ guacamole_temp_path }}'
    state: absent
  changed_when: False
